### ISSUE TITLE
Ensure eventually generated folders contain `__init__.py` files

### ISSUE THREAD

**Issue by ZanSara** [addisonElliott/pyqt5ac#10]
Folders into Python packages are always required to contain a `__init__.py` file, or otherwise they might not be recognized as submodules and imports can fail.

Currently pyqt5ac creates new folders if required, but it does not ensure the presence of such `__init__.py` and therefore the generated files might fail to import.

In #3 I proposed a patch that will make sure that at least the folder containing the files includes as well an `__init__.py`. I haven't tested it over more nested setups, hopefully it's a rare use-case, but in any case it seems rather simple to extend at need.
it also comes with a flag called `--no-init` to disable such check at need.

**Comment by zkovari** [comment]
I'm in favor of creating the `__init__.py` files, I just don't really like the current naming. What about `--init-package` with a default value of True?

Furthermore, the option should be available on the command line as well as in the input configuration file (yml). Plus it should be documented and tested.

@ZanSara would you like to work on this one or shall I assign to myself?

**Comment by ZanSara** [comment]
That's a very small modification to do, so I can do it (docs & tests included ofc), but I would wait for a clarification on the tests issue before submitting more PRs (see #22). For the naming I don't mind, I'll use `--init-package` then.

**Comment by zkovari** [comment]
ok, thanks! I assign to you then.

Regarding the tests, I think the following test cases should be considered:
- `__init__.py` is generated by default in output directory
- `__init__.py` generation can be disabled
- `__init__.py` is **not** re-created if already exists

Currently we don't test the command line interface itself but rather invoke the module's main method. So it's okay if you follow the same approach.

**Comment by zkovari** [comment]
1.2.0 was released. Thanks a lot!
