### ISSUE TITLE
Set up webhook to GitLab mirror repository

### ISSUE THREAD

**Issue by zkovari** [addisonElliott/pyqt5ac#16]
Set up a webhook to the corresponding GitLab repository: https://gitlab.com/zkovari/pyqt5ac

Steps to do so:
- Create a Personal access token on GitLab. Ref: https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html. Scope should be API.
- Add a webhook to the GitHub repository to trigger the pipeline on each push. Reference: point 5 in https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html#connect-manually

The webhook setup should point to 
`https://gitlab.com/api/v4/projects/17788428/mirror/pull?private_token=<PERSONAL_ACCESS_TOKEN>`, replacing with your GitLab personal access token. Content type is `application/json`. Event is push event.

Expected outcome: a push event on GitHub would automatically trigger a pipeline on GitLab.

**Comment by zkovari** [comment]
@addisonElliott could you set this up, please? I cannot add webhooks to the repo. Let me know if you have any questions. Thank you.

**Comment by addisonElliott** [comment]
Sure, so I have the webhook setup but it's giving me 403, unauthorized access.

Can you create a personal access token and then send it to me (however you want to securely do it)?

I am thinking it's because I don't own the repository? Not sure.

**Comment by zkovari** [comment]
Hm, I added you as a develop before, now I changed your access to maintainer. Could you try it again please? But honestly even developer should be enough, weird.

**Comment by addisonElliott** [comment]
Alright, that did it. The webhook says it's all setup.

Not sure if you need anything else from me. I didn't see the tests run for my PR though?

**Comment by zkovari** [comment]
it works well, thanks a lot!

I think you just didn't have the latest change from master which included the pipeline config. Now I tested with a new branch, the ci is triggered.

**Comment by addisonElliott** [comment]
That makes sense. I forgot to pull from master before creating my new branch. Sounds good, closing this.

**Comment by zkovari** [comment]
and the pipeline's status also appears on the commit on GitHub since we have a github integration set up on GitLab. Yeah I know it's a bit sophisticated but gitlab ci is so powerful. So yes looks good. Thanks a lot!
