### ISSUE TITLE
Set up codeclimate integration

### ISSUE THREAD

**Issue by zkovari** [addisonElliott/pyqt5ac#17]
Add the repository on https://codeclimate.com/dashboard.

After that, under Repo Settings -> Plugins, select the following:
-  Fixme
- Git.legal
- Markdownlint
- Pep8
- Radon
- SonarPython

After the setup, it might require some time to run the analysis. And probably it will be only triggered on the next commit.

**Comment by zkovari** [comment]
@addisonElliott could you set this up as well please? I like using codeclimate nowadays, and it's free for open source projects. I haven't used it for python yet, for Java it's not so bad.

**Comment by addisonElliott** [comment]
👍 Done

**Comment by zkovari** [comment]
Thanks!

For ref: https://codeclimate.com/github/addisonElliott/pyqt5ac
