### ISSUE TITLE
Define custom variables

### ISSUE THREAD

**Issue by ZanSara** [addisonElliott/pyqt5ac#2]
Currently I see that three variables can be used to specify the name and location of the files to convert: FILENAME, EXT and DIRNAME. 

Is there any way to define extra variables? A practical example:

`config.yml`
```
variables:
- BASEDIR: my_project_name
ioPaths:
  -
    - "%%BASEDIR%%/gui/*.ui"
    - "%%BASEDIR%%/generated/%%FILENAME%%_ui.py"
uic_options: --from-imports
force: False
```
That would be allow me to put the configuration file in the root of the project, so it doesn't get packaged when I release the code.

**Comment by addisonElliott** [comment]
Hello,

Great question, but alas I did not think that far ahead.

It's pretty easy to add new variables, you can see how I did it in the source code: https://github.com/addisonElliott/pyqt5ac/blob/master/pyqt5ac.py#L170-L172

PRs are welcome!

**Comment by zkovari** [comment]
Hi Sara,

And would you like to override this variable through the command line in order to use the same config for different projects? Or why is it necessary to use a separate variable? Why not to just declare:

```
ioPaths:
  -
    - "my_project_name/gui/*.ui"
    - "my_project_name/generated/%%FILENAME%%_ui.py"
```

or even this should work (I didn't try though):
```
ioPaths:
  -
    - "*/gui/*.ui"
    - "%%DIRNAME%%/generated/%%FILENAME%%_ui.py"
```
But maybe I miss something.

**Comment by ZanSara** [comment]
What I am making at the moment is a template base PyQt5 application, so I expect the package name to be configurable to some degree. This said, my specific problem is in how I would like the *.qrc files to be compiled.
For example, I have this structure:
```
my_project/
`--- gui
     |--- resources
     |    |--- image.png
     |    `--- resources.qrc  <-- this one...
     |--- interface.ui
     `--- generated
          |---interface_ui.py
          `---resources_rc.py  <--- ...becomes this
```
This would translate, I guess, into this config file:
```
ioPaths:
  -
    - "*/gui/*.ui"
    - "%%DIRNAME%%/generated/%%FILENAME%%_ui.py"
  -
    - "*/resources/*.qrc"
    - "%%DIRNAME%%/../generated/%%FILENAME%%_ui.py"
```
Which, to be honest, starts to look confusing with respect to
```
variables:
  BASEDIR: `my_project`
ioPaths:
  -
    - "%%BASEDIR%%/gui/*.ui"
    - "%%BASEDIR%%/gui/generated/%%FILENAME%%_ui.py"
  -
    - "%%BASEDIR%%/gui/resources/*.qrc"
    - "%%BASEDIR%%/gui/generated/%%FILENAME%%_rc.py"
```
In addition, relative paths might cause trouble as, in most cases, the user wants the code generated from *ui files and *.qrc to fall in the same folder in order for the relative import to work.

Just my opinion. In addition, implementation seems trivial atm, I will send over a pull request soon.

**Comment by zkovari** [comment]
@ZanSara thanks! PR was merged. I will add some finishing touches.
