### ISSUE TITLE
Tests seems to be not independent

### ISSUE THREAD

**Issue by ZanSara** [addisonElliott/pyqt5ac#22]
In #3 I added a check on the `variables` dictionary. Running the tests before introducing modifications showed no issue. However, after introducing that simple check over the input, it seems like the tests have an issue and they are not independent.

How to reproduce:
1. Get the code from PR #3
2. ` pip install pytest pytest-random-order`  (btw, this was a guess and it wouldn't be necessary if test dependencies were specified in `setup.py`, see #21)
3. `python -m pytest`  --> 7 tests fail: `variables` apparently contains the default keys already.
4. `python -m pytest --random-order`  --> 8 tests fail: same reason.
5. `python -m pytest tests/test_pyqt5ac.py::test_resource_generation` --> passes
6.  `python -m pytest tests/test_pyqt5ac.py::<any other failed test>` --> passes (I tested them all one by one)

I recommend having a look at pytest documentation in any case. Or, if you're using any other framework for testing and this is a consequence of a wrong guess, please document it somewhere and I'll retry.

**Comment by zkovari** [comment]
I have to check but in theory they are all using separate dedicated temporary folders and files for the input+generated output. So there shouldn't be any shared resource among them. What is the error by the way?

And yes, pytest it is.

**Comment by ZanSara** [comment]
Ok, I found the issue and actually it was introduced by me. I've honestly never seen such behavior before: apparently, CLI interfaces should never leave the default of the last argument taken as a mutable type, as apparently it picks up garbage. 

Maybe it's a Click bug? I haven't checked yet. However, I fixed it, now tests work. Sorry for the spam.
