### ISSUE TITLE
Set up auto publication to Pypi repository

### ISSUE THREAD

**Issue by zkovari** [addisonElliott/pyqt5ac#4]
Set up a Travis pipeline that can publish the package to Pypi repository. 

Release could be triggered based on a tag.

**Comment by zkovari** [comment]
@addisonElliott could you set up the travis config please? Then the next release could be done via that approach. Thank you.

**Comment by zkovari** [comment]
You can also set up secret variables on travis directly and limit to certain branches: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

**Comment by addisonElliott** [comment]
@zkovari Alright, I have it setup and tested it with version v1.0.4 and it worked.

However, I want to mention that the Travis CI setup is a bit kludgy but it works. I'll leave it up to you, but a better approach in my opinion would be to use GitHub actions to publish to PyPi. I think you can set it up basically and then I would just add the secret password for my account to publish to PyPi.

**Comment by zkovari** [comment]
@addisonElliott thanks for the quick resolution!

I agree, we can give a try to GitHub actions. I opened a pull request which uses the GitHub's template action for publishing Python packages.

**Comment by zkovari** [comment]
1.1.0 was released with the GitHub action. Thanks a lot!
